// All duty-related constants and configuration values for the Twine SugarCube project.
// This module attaches values to the global `setup` object.

export function registerDutyConstants(setup: any) {
  // how much is the multiplier per skill total?
  setup.DUTY_SKILL_MULTIPLIER_TOTAL = 0.008;

  // how much chance increase from "normal" traits?
  setup.DUTY_TRAIT_NORMAL_CHANCE = 0.1;

  // from "crit" traits?
  setup.DUTY_TRAIT_CRIT_CHANCE = 0.3;

  setup.DUTY_TRAIT_PRESTIGE1 = 1;
  setup.DUTY_TRAIT_PRESTIGE2 = 2;
  setup.DUTY_TRAIT_PRESTIGE3 = 3;
  setup.DUTY_TRAIT_PRESTIGE4 = 4;
  setup.DUTY_TRAIT_PRESTIGE5 = 5;
  setup.DUTY_TRAIT_PRESTIGE6 = 6;

  // gain prestige every this much value:
  setup.DUTY_VALUE_PRESTIGE_GAINS = [5000, 10000, 17000, 25000, 35000];

  // weekly upkeep for contract specialists
  setup.DUTY_SPECIALIST_WEEKLY_UPKEEP = 900;

  // how many of weeks of injuries cured by doctors
  setup.DOCTOR_ATTEMPTS = 3;
  // how many of weeks of injuries cured by doctors on critical
  setup.DOCTOR_ATTEMPTS_CRIT = 5;

  // how many leveling attempts do the drill sergeant get each week?
  setup.DRILL_SERGEANT_ATTEMPTS = 5;

  // how many crit leveling attempts do the drill sergenat get each week? I.e., these attempts
  // are triggered with (success chance - 1.0) chance.
  setup.DRILL_SERGEANT_ATTEMPTS_CRIT = 5;

  // how much money leader makes on their duty?
  setup.LEADER_MONEY = 500;
  setup.LEADER_MONEY_CRIT = 700;

  // maximum weeks of extra boon granted by mystic on crit
  setup.MYSTIC_MAX_BOON = 5;
  setup.MYSTIC_MAX_BOON_CRIT = 10;

  // boon is increased by this much on success
  setup.MYSTIC_BOON_MULTI = 0.5;

  // boon is increased by this much on crit
  setup.MYSTIC_BOON_MULTI_CRIT = 1.0;

  // slave orders generated by marketers expire after this many weeks
  setup.MARKETER_ORDER_EXPIRATION = 2;

  // slave order price on critical marketer are multiplied by this much
  setup.MARKETER_CRIT_MULTIPLIER = 1.5;

  // profit per prestige from pimp
  setup.PIMP_PRESTIGE_MULTIPLIER = 50;

  // each pimp can manage at most this many slaves
  setup.PIMP_SLAVE_LIMIT = 3;

  // profit multiplied by this on pimp crit
  setup.PIMP_CRIT_MULTIPLIER = 1.5;

  // profit on critical pimp are multiplied by this much
  setup.MARKETER_CRIT_MULTIPLIER = 1.5;

  // on scout critical, this many quests are generated.
  setup.SCOUTDUTY_CRIT_MULTIPLIER = 1.5;

  // how much slave value is worth 1 prestige?
  setup.PRESTIGESLAVE_SLAVE_VALUE_FOR_ONE_PRESTIGE =
    6 * setup.MONEY_PER_SLAVER_WEEK;

  // how much does your vice leader improve your skills?
  setup.VICELEADER_SKILL_MULTI = 0.12;

  setup.TRAINER_MAX_LEVEL = 35;
  setup.TRAINER_CRIT_EXP_MULTI = 1.7;

  // How much percent of the money insurer gives on these outcomes?
  setup.INSURER_MULTIS = {
    failure: {
      proc: 2.0 / 3.0,
      crit: 1.0,
    },
    disaster: {
      proc: 1.0,
      crit: 1.4,
    },
  };
}
